import { User, TrackInfo, Wave, Playlist, Challenge } from '@/types';

export const dummyUsers: User[] = [
  {
    id: '1',
    nickname: '김음악',
    profileImage: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face',
    email: 'kim@example.com',
    youtubeChannelUrl: 'https://www.youtube.com/channel/UClvAWsgaBdalIjxBIwmbULg',
    followers: 1234,
    following: 567,
    preferences: {
      genres: ['K-Pop', 'Hip-Hop', 'Electronic'],
      notifications: {
        newWaves: true,
        comments: true,
        challenges: false,
      },
    },
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    nickname: '박플레이',
    profileImage: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face',
    email: 'park@example.com',
    youtubeChannelUrl: 'https://www.youtube.com/channel/UClvAWsgaBdalIjxBIwmbULg',
    followers: 890,
    following: 234,
    preferences: {
      genres: ['Rock', 'Indie', 'Jazz'],
      notifications: {
        newWaves: true,
        comments: true,
        challenges: true,
      },
    },
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z',
  },
  {
    id: '3',
    nickname: '이리듬',
    profileImage: 'https://images.unsplash.com/photo-1494790108755-2616b612b786?w=100&h=100&fit=crop&crop=face',
    email: 'lee@example.com',
    youtubeChannelUrl: 'https://www.youtube.com/channel/UClvAWsgaBdalIjxBIwmbULg',
    followers: 2100,
    following: 890,
    preferences: {
      genres: ['Electronic', 'Hip-Hop', 'Pop'],
      notifications: {
        newWaves: true,
        comments: false,
        challenges: true,
      },
    },
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
  },
];

export const dummyTracks: TrackInfo[] = [
  {
    id: '1',
    title: 'Dynamite',
    artist: 'BTS',
    album: 'BE',
    platform: 'youtube',
    externalId: 'gdZLi9oWNZg',
    thumbnailUrl: 'https://img.youtube.com/vi/gdZLi9oWNZg/mqdefault.jpg',
    duration: 199,
  },
  {
    id: '2',
    title: 'Blinding Lights',
    artist: 'The Weeknd',
    album: 'After Hours',
    platform: 'youtube',
    externalId: '4NRXx6U8ABQ',
    thumbnailUrl: 'https://img.youtube.com/vi/4NRXx6U8ABQ/mqdefault.jpg',
    duration: 200,
  },
  {
    id: '3',
    title: 'Levitating',
    artist: 'Dua Lipa',
    album: 'Future Nostalgia',
    platform: 'youtube',
    externalId: 'TUVcZdfc1uo',
    thumbnailUrl: 'https://img.youtube.com/vi/TUVcZdfc1uo/mqdefault.jpg',
    duration: 203,
  },
  {
    id: '4',
    title: 'Good 4 U',
    artist: 'Olivia Rodrigo',
    album: 'SOUR',
    platform: 'youtube',
    externalId: 'gNi_6U5Pm_o',
    thumbnailUrl: 'https://img.youtube.com/vi/gNi_6U5Pm_o/mqdefault.jpg',
    duration: 178,
  },
  {
    id: '5',
    title: 'Stay',
    artist: 'The Kid LAROI & Justin Bieber',
    album: 'F*CK LOVE 3',
    platform: 'youtube',
    externalId: 'kTJczUoc26U',
    thumbnailUrl: 'https://img.youtube.com/vi/kTJczUoc26U/mqdefault.jpg',
    duration: 141,
  },
];

export const dummyWaves: Wave[] = [
  {
    id: '1',
    user: dummyUsers[0],
    track: dummyTracks[0],
    comment: '아침에 듣기 좋은 에너지 넘치는 곡! 🔥',
    moodEmoji: '🔥',
    moodText: '에너지',
    timestamp: new Date(Date.now() - 86400000).toISOString(),
    likes: 24,
    comments: 8,
    saves: 12,
    shares: 3,
    isLiked: false,
    isSaved: false,
  },
  {
    id: '2',
    user: dummyUsers[1],
    track: dummyTracks[1],
    comment: '밤에 운전할 때 듣는 곡. 분위기 최고!',
    moodEmoji: '🌙',
    moodText: '밤의 분위기',
    timestamp: new Date(Date.now() - 172800000).toISOString(),
    likes: 18,
    comments: 5,
    saves: 9,
    shares: 2,
    isLiked: true,
    isSaved: false,
  },
  {
    id: '3',
    user: dummyUsers[2],
    track: dummyTracks[2],
    comment: '춤추고 싶어지는 리듬이에요 💃',
    moodEmoji: '💃',
    moodText: '춤추고 싶어',
    timestamp: new Date(Date.now() - 259200000).toISOString(),
    likes: 31,
    comments: 12,
    saves: 15,
    shares: 7,
    isLiked: false,
    isSaved: true,
  },
  {
    id: '4',
    user: dummyUsers[0],
    track: dummyTracks[3],
    comment: '운동할 때 듣는 곡. 힘이 나요!',
    moodEmoji: '💪',
    moodText: '운동',
    timestamp: new Date(Date.now() - 345600000).toISOString(),
    likes: 15,
    comments: 3,
    saves: 7,
    shares: 1,
    isLiked: true,
    isSaved: true,
  },
  {
    id: '5',
    user: dummyUsers[1],
    track: dummyTracks[4],
    comment: '감정이 복잡할 때 듣는 곡',
    moodEmoji: '😭',
    moodText: '감정적',
    timestamp: new Date(Date.now() - 432000000).toISOString(),
    likes: 22,
    comments: 9,
    saves: 11,
    shares: 4,
    isLiked: false,
    isSaved: false,
  },
];

export const dummyPlaylists: Playlist[] = [
  {
    id: '1',
    title: '스터디 플레이리스트',
    description: '집중할 때 듣기 좋은 곡들',
    creator: dummyUsers[0],
    tracks: dummyTracks.slice(0, 3),
    isPublic: true,
    isCollaborative: false,
    likes: 156,
    saves: 89,
    plays: 1203,
    thumbnailUrl: 'https://img.youtube.com/vi/gdZLi9oWNZg/mqdefault.jpg',
    createdAt: '2024-01-01T00:00:00Z',
    updatedAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    title: '운동할 때 듣는 음악',
    description: '에너지 넘치는 운동 BGM',
    creator: dummyUsers[1],
    tracks: dummyTracks.slice(1, 4),
    isPublic: true,
    isCollaborative: true,
    likes: 234,
    saves: 167,
    plays: 2105,
    thumbnailUrl: 'https://img.youtube.com/vi/4NRXx6U8ABQ/mqdefault.jpg',
    createdAt: '2024-01-02T00:00:00Z',
    updatedAt: '2024-01-02T00:00:00Z',
  },
  {
    id: '3',
    title: '밤의 감성 플레이리스트',
    description: '밤에 혼자 있을 때 듣기 좋은 곡들',
    creator: dummyUsers[2],
    tracks: dummyTracks.slice(2, 5),
    isPublic: true,
    isCollaborative: false,
    likes: 189,
    saves: 134,
    plays: 1567,
    thumbnailUrl: 'https://img.youtube.com/vi/TUVcZdfc1uo/mqdefault.jpg',
    createdAt: '2024-01-03T00:00:00Z',
    updatedAt: '2024-01-03T00:00:00Z',
  },
];

export const dummyChallenges: Challenge[] = [
  {
    id: '1',
    title: '스터디 플레이리스트 챌린지',
    description: '집중할 때 듣기 좋은 곡들을 추천해주세요!',
    creator: dummyUsers[0],
    status: 'active',
    startDate: '2024-01-01T00:00:00Z',
    endDate: '2024-01-15T00:00:00Z',
    votingEndDate: '2024-01-20T00:00:00Z',
    targetTrackCount: 20,
    currentTrackCount: 15,
    participants: 45,
    rules: {
      genres: ['Electronic', 'Classical', 'Ambient'],
      moods: ['집중', '평온'],
      allowDuplicates: false,
      votingMethod: 'like',
    },
    thumbnailUrl: 'https://img.youtube.com/vi/gdZLi9oWNZg/mqdefault.jpg',
    createdAt: '2024-01-01T00:00:00Z',
  },
  {
    id: '2',
    title: '운동 BGM 챌린지',
    description: '운동할 때 듣기 좋은 에너지 넘치는 곡들을 추천해주세요!',
    creator: dummyUsers[1],
    status: 'voting',
    startDate: '2023-12-15T00:00:00Z',
    endDate: '2023-12-30T00:00:00Z',
    votingEndDate: '2024-01-05T00:00:00Z',
    targetTrackCount: 25,
    currentTrackCount: 25,
    participants: 78,
    rules: {
      genres: ['Hip-Hop', 'Electronic', 'Rock'],
      moods: ['에너지', '흥분'],
      allowDuplicates: false,
      votingMethod: 'rating',
    },
    thumbnailUrl: 'https://img.youtube.com/vi/4NRXx6U8ABQ/mqdefault.jpg',
    createdAt: '2023-12-15T00:00:00Z',
  },
  {
    id: '3',
    title: '겨울 감성 플레이리스트',
    description: '겨울에 듣기 좋은 따뜻한 감성의 곡들을 추천해주세요!',
    creator: dummyUsers[2],
    status: 'upcoming',
    startDate: '2024-01-20T00:00:00Z',
    endDate: '2024-02-05T00:00:00Z',
    votingEndDate: '2024-02-10T00:00:00Z',
    targetTrackCount: 30,
    currentTrackCount: 0,
    participants: 0,
    rules: {
      genres: ['Indie', 'Folk', 'Acoustic'],
      moods: ['따뜻', '감성적'],
      allowDuplicates: false,
      votingMethod: 'ranking',
    },
    thumbnailUrl: 'https://img.youtube.com/vi/TUVcZdfc1uo/mqdefault.jpg',
    createdAt: '2024-01-10T00:00:00Z',
  },
];
